apiVersion: v1
kind: Secret
metadata:
  name: banking-secret
  namespace: go-banking
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgres@postgres:5432/go_banking?sslmode=disable"
  JWT_SECRET: "local_k8s_secret_change_later"
