apiVersion: batch/v1
kind: Job
metadata:
  name: banking-migration
  namespace: go-banking
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: 348362971250.dkr.ecr.us-east-1.amazonaws.com/go-banking-api:latest
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - |
              ./goose -dir ./migrations postgres "$DATABASE_URL" up
          envFrom:
            - secretRef:
                name: banking-secret
