apiVersion: v1
kind: Secret
metadata:
  name: banking-secret
  namespace: go-banking
type: Opaque
stringData:
  DATABASE_URL: "postgres://USERNAME:PASSWORD@YOUR_RDS_ENDPOINT:5432/go_banking?sslmode=require"
  JWT_SECRET: "CHANGE_ME"
